hljs.registerLanguage('abap', function(hljs) {
  var KEYWORDS = {
    $pattern: /[A-Za-z_]\w*/,
    keyword: {
      className: 'keyword',
      begin: /\b(?:ABAP|ABSTRACT|ACCEPT|ACCORDING|ACTIVATE|ACTUAL|ADD|AFTER|ALIAS|ALIGN|ALL|ALPHANUMERIC|ANALYTICAL|AND|APPEND|ARCHIVE|AREA|AS|ASCENDING|ASPECT|ASSIGN|ASSOCIATION|AT|AUTHORITY|AUTHORIZATION|AUTHORIZATION_CHECK|AVG|BACK|BACKUP|BEFORE|BEGIN|BETWEEN|BINARY|BLOCK|BOUND|BREAK|BROWSER|BUT|BY|CALCULATION|CALL|CANCEL|CASE|CAST|CDS|CHAIN|CHANGE|CHANGING|CHECK|CLASS|CLASSIFICATION|CLEAN|CLEAR|CLIENT|CLOUD|COALESCE|COLLECT|COLUMN|COLUMNS|COMMIT|COMMUNICATION|COMPARING|COMPILE|COMPILER|COMPONENT|COMPONENTS|COMPOSITE|COMPOSITION|COMPRESSION|CONCAT|CONDITION|CONFIGURATION|CONNECT|CONNECTION|CONSTANTS|CONSUMPTION|CONTEXT|CONTRACT|CONTROL|CONVERSION|COPY|COUNT|CREATE|CREATING|CROSS|CUBE|CURRENCY|CURRENCY_CODE|CURRENT|CURSOR|CUSTOMER|CUSTOMIZING|DATA|DATABASE|DATACATEGORY|DATE|DAY|DDIC|DEACTIVATE|DEALLOCATE|DEC|DECIMAL|DECIMALS|DECLARATIONS|DEEP|DEFAULT|DEFERRED|DEFINE|DEFINITION|DELETE|DELETING|DEPARTMENT|DEPENDENT|DEPTH|DESC|DESCENDING|DESCRIBE|DESCRIPTION|DESTINATION|DETAIL|DETAILS|DIRECTORY|DISCONNECT|DISPLAY|DISTINCT|DIVIDE|DRAFT|DROP|DUMMY|DUPLICATE|DURATION|DURING|DYNAMIC|EACH|EDIT|ELEMENT|ELEMENTS|ELSE|EMPTY|ENABLE|ENABLING|END|ENDCASE|ENDDO|ENDENHANCEMENT|ENDEXEC|ENDFORM|ENDFUNCTION|ENHANCEMENT|ENDIF|ENDLOOP|ENDMETHOD|ENDMODULE|ENDPROGRAM|ENDSELECT|ENDTRY|ENDWHILE|ENGINEERING|ENTITY|ENTRY|ENUM|EQUIVALENT|ERROR|ESCAPE|EVENT|EVENTS|EXACT|EXCEPTION|EXCEPTIONS|EXEC|EXECUTE|EXISTS|EXIT|EXPLICIT|EXPORT|EXPOSURE|EXPOSURE|EXPRESS|EXTEND|EXTENDED|EXTENSION|EXTERNAL|EXTRACT|FAIL|FALLBACK|FALSE|FIELD|FIELDS|FILE|FILTER|FINAL|FIND|FIRST|FIXED|FLOAT|FLUSH|FOLLOWING|FOOTER|FOR|FORM|FORMAT|FORWARD|FOUND|FRAME|FREE|FROM|FUNCTION|FUNCTIONALITY|FUNCTION_IMPORT|GENERATE|GENERATED|GET|GIVING|GLOBAL|GOTO|GRANT|GRID|GROUP|HANDLE|HANDLER|HARMLESS|HAVING|HEADER|HEADERS|HELP|HIERARCHY|HIGH|HOLD|HOUR|ICON|ID|IDENTIFICATION|IDENTIFIER|IF|IGNORE|IMMEDIATELY|IMPLEMENTATION|IMPLEMENTED|IMPLICIT|IMPORT|INCLUDING|INCLUSIVE|INDEX|INDEXES|INDICATOR|INFOTYPE|INHERITING|INITIAL|INNER|INPUT|INSERT|INSTANCE|INTEFACE|INTEGER|INTENSIFIED|INTERFACE|INTERNAL|INTERVAL|INTO|INVALID|INVOKE|IS|ISOLATION|JOB|JOIN|JSON|KEEP|KEY|KEYS|KEYWORD|KIND|LANGUAGE|LAST|LAYER|LEADING|LEAVE|LEFT|LENGTH|LESS|LEVEL|LEVELS|LIKE|LINE|LINES|LIST|LOAD|LOADING|LOCAL|LOCALE|LOCATION|LOG|LOGICAL|LONG|LOOP|LOW|MAIN|MAINTAIN|MAINTENANCE|MAJOR|MANAGED|MAPPING|MASK|MASTER|MATCH|MATCHCODE|MAX|MAXIMUM|MEMBER|MEMBERS|MESH|MESSAGE|MESSAGES|METHOD|METHODS|MIN|MINIMUM|MINOR|MINUTE|MODE|MODEL|MODIFICATION|MODIFY|MODULE|MONTH|MULTIPLE|MULTIPLICITY|NAME|NAMES|NATIVE|NAVIGATION|NESTED|NEW|NEXT|NO|NODE|NODES|NON|NOT|NULL|NUMBER|NUMERIC|OCCURRENCE|OCCURS|OF|OFF|ON|ONLY|OPEN|OPERATION|OPERATIONS|OPTION|OPTIONAL|OPTIONS|OR|ORDER|ORGANIZATION|OTHER|OTHERS|OUTER|OUTPUT|OVER|OVERLAY|PACKAGE|PADDING|PAGE|PAGING|PARAMETER|PARAMETERS|PARENT|PART|PATH|PATTERN|PERCENTAGE|PERFORM|PERFORMANCE|PERSON|PFCD|PFCG|PREFERRED|PRESERVE|PRIMARY|PRINT|PRIVILEGED|PRIVILEGES|PROCEDURE|PROCESSING|PRODUCT|PROFILE|PROGRAM|PROJECTION|PROPERTY|PROTOCOL|PROVIDER|PROXY|PUBLIC|PURGE|PURPOSE|PUT|QUALIFIER|QUANTITY|QUERY|QUEUE|RANGE|RANK|RAP|RAW|READ|READER|READ_ONLY|READS|RECEIVE|RECEIVER|RECORDS|REDIRECT|REDUCE|REF|REFERENCE|REFRESH|REGEX|REGISTER|REJECT|RELATION|RELEASE|REMOTE|RENAME|REPEAT|REPLACE|REPLICATION|REPORT|REQUEST|REQUIRE|REQUIRED|RESERVE|RESET|RESOLUTION|RESOURCE|RESPONSE|RESTORE|RESULT|RESULTS|RESUME|RETAIN|RETRIEVAL|RETURN|RETURNING|REUSE|REVERSE|REVOKE|RIGHT|ROLE|ROLLBACK|ROOT|ROUND|ROUTINE|ROW|ROWS|RUN|SAFE|SAVING|SCALE|SCENARIO|SCHEMA|SCORE|SCREEN|SCROLL|SEARCH|SECOND|SECONDARY|SECONDS|SECURE|SECURITY|SEGMENT|SELECT|SELECTION|SELECT_OPTIONS|SEMANTICS|SEND|SEPARATE|SEQUENCE|SERIAL|SERIALIZABLE|SERVER|SERVICE|SESSION|SET|SHARED|SHIFT|SHORT|SIGN|SIGNATURE|SIMPLE|SINGLE|SIZE|SKIP|SMALL|SOME|SORT|SORTED|SOURCE|SPACE|SPECIFIED|SPLIT|SQL|STANDARD|START|STATEMENT|STATIC|STATISTICS|STATUS|STOP|STORAGE|STORE|STRING|STRUCTURE|STYLE|SUB|SUBMATCH|SUBSCREEN|SUBSTRING|SUBTRACT|SUFFIX|SUM|SUMMARY|SUPPLEMENT|SUPPLY|SUPPORT|SUPPRESS|SWITCH|SYMBOL|SYNCPOINTS|SYNTAX|SYSTEM|TABLE|TABLES|TARGET|TASK|TASKS|TECHNICAL|TEST|TEXT|THAN|THEN|THROW|TIME|TIMES|TIMESTAMP|TO|TOKEN|TOP|TRACE|TRACT|TRANSACTION|TRANSFER|TRANSFORMATION|TRANSPORT|TRIGGER|TRIM|TRUE|TRUNCATE|TRY|TURN|TYPE|TYPES|TYPING|UI|UNASSIGN|UNDER|UNIT|UNITS|UNIVERSAL|UNKNOWN|UNNEST|UNPACK|UNTIL|UNWIND|UPDATE|UPDATING|UPGRADE|URL|USAGE|USE|USER|USING|VALID|VALIDATE|VALIDATION|VALUE|VALUES|VARY|VDM|VERSION|VIA|VIEW|VIRTUAL|VISIBILITY|WAIT|WARNING|WEB|WEEK|WHEN|WHERE|WHILE|WIDTH|WINDOW|WITH|WITHOUT|WORK|WRITE|WRITER|XML|YEAR|ZERO|ZONE)\b/i
    },
    builtIn: {
      className: 'built_in',
      begin: /\b(?:abap\.(?:char|numc|string|int4|int8|dec|float16|hex|boolean|dats|tims|utclong)|string|int4|int8|dec|float|char|numc|clnt|cust|lang|boolean|dats|tims|utclong)\b/i
    }
  };

  var ANNOTATION = {
    className: 'doctag',
    begin: /@\w+(?:\.\w+)*(?:\s*:\s*'[^']*'|\s*:\s*#[A-Z_]+|\s*:\s*true|\s*:\s*false)?/,
    relevance: 0
  };

  var STRING = {
    className: 'string',
    begin: /'/,
    end: /'/,
    contains: [{begin: /''/}],
    relevance: 0
  };

  var NUMBER = {
    className: 'number',
    begin: /\b\d+(?:\.\d+)?(?:\.\d+)?\b/,
    relevance: 0
  };

  var COMMENT_BLOCK = {
    className: 'comment',
    variants: [
      {begin: /\/\*/, end: /\*\//},
      {begin: /"/, end: /$/}
    ]
  };

  var OPERATORS = {
    className: 'operator',
    begin: /=>|->|\|/
  };

  return {
    name: 'ABAP CDS',
    aliases: ['abapcds'],
    case_insensitive: true,
    keywords: KEYWORDS,
    contains: [
      ANNOTATION,
      COMMENT_BLOCK,
      STRING,
      NUMBER,
      OPERATORS,
      {
        className: 'symbol',
        begin: /:/
      }
    ]
  };
});
